
version: '3'

services:

  www:
    build: './front/www'
    volumes:
      - './front/www/html:/usr/share/nginx/html'
    ports:
      - '2200:80'

  panel:
    build: './front/panel'
    volumes:
      - './front/panel/html:/usr/share/nginx/html'
    ports:
      - '3300:80'

