version: '3'

services:
  panel:
    build: './src/front/panel'
    volumes:
      - './src/front/panel/html:/usr/share/nginx/html'
    ports:
      - '80:80'
  api_users_register:
    hostname: api_users_register
    build: './src/api/users-register'
    env_file:
      - './docker-compose.env'
    restart: always
    volumes:
      - './src/api/users-register:/iovel/app'
      - './src/commons:/iovel/commons'
      - './data:/iovel/data'
  api_users_login:
    hostname: api_users_login
    build: './src/api/users-login'
    env_file:
      - './docker-compose.env'
    restart: always
    volumes:
      - './src/api/users-login:/iovel/app'
      - './src/commons:/iovel/commons'
      - './data:/iovel/data'
